In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = pd.read_csv("./data/mud_props_UTF.csv")

In [3]:
data

,Well,Date,Time,Mud Wt. In (ppg),Mud Wt. Out (ppg),Temp Out deg Â°F,Funnel Viscosity,Fann 600 rpm,Fann 300 rpm,Fann 200 rpm,...,HTHP (Cake mm),Water %,Retort Solids %,Corrected Solids %,Oil%,Sand %,Solids ASG,LGS %,HGS %,MBT
0,OVHOR - 13,7/16/2012,8:00HRS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,15:00HRS,8.9,8.9,NaN,65.0,65.0,50.0,42.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,24:00HRS,8.9,8.9,NaN,65.0,65.0,50.0,42.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,7/17/2012,8:00HRS,8.7,8.7,NaN,80.0,35.0,29.0,21.0,...,NaN,98.0,2.0,NaN,NaN,0.8,NaN,NaN,NaN,20.0
4,NaN,NaN,15:00HRS,8.7,8.7,NaN,80.0,35.0,29.0,21.0,...,NaN,98.0,2.0,NaN,NaN,0.8,NaN,NaN,NaN,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,NaN,NaN,16:00HRS,10.0,NaN,NaN,67.0,61.0,44.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
578,NaN,NaN,24:00HRS,10.0,NaN,NaN,66.0,61.0,45.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
579,NaN,2/7/2024,8:00HRS,10.0,NaN,NaN,67.0,61.0,45.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
580,NaN,NaN,16:00HRS,10.0,NaN,NaN,67.0,61.0,45.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
581,NaN,NaN,24:00HRS,10.0,NaN,NaN,69.0,62.0,46.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.isna().sum()

Well                             564
Date                             388
Time                               0
Mud Wt. In (ppg)                   2
Mud Wt. Out  (ppg)               120
Temp Out deg Â°F                  367
Funnel Viscosity                   4
Fann 600 rpm                       3
Fann 300 rpm                       3
Fann 200 rpm                       3
Fann 100 rpm                       3
Fann 6 rpm                         5
Fann 3 rpm                         8
Plastic Viscosity (lb/100ftÂ²)      3
Yield Point (lb/100ftÂ²)            3
Gel 10Sec (lb/100ftÂ²)             33
Gel 10min (lb/100ftÂ²)             35
n                                  4
K                                 40
API Fluid Loss (ml)               35
Cake mm                           71
pH                                18
Pm                               355
Pf                               328
Mf                               328
Chloride mg/l                    150
Ca+ mg/l                         160
NaO mg/l                         582
KCl ppb                          135
K+ mg/l                          137
HTHP Water(ml)                   582
HTHP (Cake mm)                   582
Water %                           60
Retort Solids  %                  61
Corrected Solids %               208
Oil%                             180
Sand %                            44
Solids ASG                       219
LGS %                            132
HGS %                            271
MBT                               21
dtype: int64

In [5]:
data.columns

Index(['Well', 'Date', 'Time', 'Mud Wt. In (ppg)', 'Mud Wt. Out  (ppg)',
       'Temp Out deg Â°F', 'Funnel Viscosity ', 'Fann 600 rpm', 'Fann 300 rpm',
       'Fann 200 rpm', 'Fann 100 rpm', 'Fann 6 rpm', 'Fann 3 rpm',
       'Plastic Viscosity (lb/100ftÂ²)', 'Yield Point (lb/100ftÂ²)',
       'Gel 10Sec (lb/100ftÂ²)', 'Gel 10min (lb/100ftÂ²)', 'n', 'K',
       'API Fluid Loss (ml)', 'Cake mm', 'pH', 'Pm', 'Pf', 'Mf',
       'Chloride mg/l', 'Ca+ mg/l', 'NaO mg/l', 'KCl ppb', 'K+ mg/l',
       'HTHP Water(ml) ', 'HTHP (Cake mm)', 'Water % ', 'Retort Solids  % ',
       'Corrected Solids %', 'Oil%', 'Sand %', 'Solids ASG', 'LGS %', 'HGS % ',
       'MBT'],
      dtype='object')

In [6]:
feature = data[['Mud Wt. In (ppg)', 'Funnel Viscosity ']]
target = data[['Fann 600 rpm', 'Fann 300 rpm']]

In [7]:
feature.shape

(582, 2)

In [11]:
feature.isnull().sum()

Mud Wt. In (ppg)     0
Funnel Viscosity     0
Fann 600 rpm         0
Fann 300 rpm         0
dtype: int64

In [10]:
numeric_columns = target.select_dtypes(include=[np.number]).columns
print("Numeric columns:", list(numeric_columns))

Numeric columns: ['Fann 600 rpm', 'Fann 300 rpm']

In [11]:
for col in numeric_columns:
    target[col] = target[col].fillna(target[col].mean())

C:\Users\user\AppData\Local\Temp\ipykernel_11512\922752383.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target[col] = target[col].fillna(target[col].mean())

In [12]:
import joblib
scaler = MinMaxScaler()
feature_normalized = pd.DataFrame(scaler.fit_transform(feature), columns=feature.columns)
joblib.dump(scaler, 'normalization_feature.pkl')

['normalization_feature.pkl']

In [13]:
import joblib
scaler = MinMaxScaler()
target_normalized = pd.DataFrame(scaler.fit_transform(target), columns=target.columns)
joblib.dump(scaler, 'normalization_target.pkl')

['normalization_target.pkl']

In [13]:
feature_normalized

     Mud Wt. In (ppg)  Funnel Viscosity   Fann 600 rpm  Fann 300 rpm
0            0.010131           0.412897      0.398015      0.367512
1            0.006612           0.320988      0.422535      0.421053
2            0.006612           0.320988      0.422535      0.421053
3            0.003306           0.506173      0.000000      0.052632
4            0.003306           0.506173      0.000000      0.052632
..                ...                ...           ...           ...
577          0.024793           0.345679      0.366197      0.315789
578          0.024793           0.333333      0.366197      0.333333
579          0.024793           0.345679      0.366197      0.333333
580          0.024793           0.345679      0.366197      0.333333
581          0.024793           0.370370      0.380282      0.350877

[582 rows x 4 columns]

In [68]:
feature

,Mud Wt. In (ppg),Mud Wt. Out (ppg),Temp Out deg Â°F,Funnel Viscosity,Fann 600 rpm,Fann 300 rpm,Fann 200 rpm,Fann 100 rpm,Fann 6 rpm,Fann 3 rpm,...,K+ mg/l,Water %,Retort Solids %,Corrected Solids %,Oil%,Sand %,Solids ASG,LGS %,HGS %,MBT
0,9.112931,8.987229,100.469767,72.444637,63.259067,46.948187,38.932642,31.132988,15.918544,13.228223,...,37030.773034,94.367625,3.992322,3.458984,2.169652,0.0001,4.060275,3.099111,0.0001,11.044029
1,8.900000,8.900000,100.469767,65.000000,65.000000,50.000000,42.000000,37.000000,25.000000,23.000000,...,37030.773034,94.367625,3.992322,3.458984,2.169652,0.0001,4.060275,3.099111,0.0001,11.044029
2,8.900000,8.900000,100.469767,65.000000,65.000000,50.000000,42.000000,37.000000,25.000000,23.000000,...,37030.773034,94.367625,3.992322,3.458984,2.169652,0.0001,4.060275,3.099111,0.0001,11.044029
3,8.700000,8.700000,100.469767,80.000000,35.000000,29.000000,21.000000,17.000000,10.000000,8.000000,...,37030.773034,98.000000,2.000000,3.458984,2.169652,0.8000,4.060275,3.099111,0.0001,20.000000
4,8.700000,8.700000,100.469767,80.000000,35.000000,29.000000,21.000000,17.000000,10.000000,8.000000,...,37030.773034,98.000000,2.000000,3.458984,2.169652,0.8000,4.060275,3.099111,0.0001,20.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,10.000000,8.987229,100.469767,67.000000,61.000000,44.000000,38.000000,36.000000,15.000000,13.000000,...,37030.773034,94.367625,3.992322,3.458984,2.169652,0.0001,4.060275,3.099111,0.0001,11.044029
578,10.000000,8.987229,100.469767,66.000000,61.000000,45.000000,39.000000,35.000000,16.000000,14.000000,...,37030.773034,94.367625,3.992322,3.458984,2.169652,0.0001,4.060275,3.099111,0.0001,11.044029
579,10.000000,8.987229,100.469767,67.000000,61.000000,45.000000,39.000000,35.000000,16.000000,14.000000,...,37030.773034,94.367625,3.992322,3.458984,2.169652,0.0001,4.060275,3.099111,0.0001,11.044029
580,10.000000,8.987229,100.469767,67.000000,61.000000,45.000000,39.000000,35.000000,16.000000,14.000000,...,37030.773034,94.367625,3.992322,3.458984,2.169652,0.0001,4.060275,3.099111,0.0001,11.044029
581,10.000000,8.987229,100.469767,69.000000,62.000000,46.000000,40.000000,35.000000,17.000000,15.000000,...,37030.773034,94.367625,3.992322,3.458984,2.169652,0.0001,4.060275,3.099111,0.0001,11.044029

In [14]:
feature_normalized.to_csv("mud_props_for_deployment_water.csv", index=False)

In [70]:
min_values = feature[['Fann 600 rpm', 'Fann 300 rpm', 'Fann 200 rpm',
       'Fann 100 rpm', 'Fann 6 rpm', 'Fann 3 rpm','API Fluid Loss (ml)']].min()
max_values = feature[['Fann 600 rpm', 'Fann 300 rpm', 'Fann 200 rpm',
       'Fann 100 rpm', 'Fann 6 rpm', 'Fann 3 rpm','API Fluid Loss (ml)']].max()

In [71]:
print(min_values)
print(max_values)

Fann 600 rpm           35.0
Fann 300 rpm           26.0
Fann 200 rpm           19.0
Fann 100 rpm           12.0
Fann 6 rpm              5.0
Fann 3 rpm              4.0
API Fluid Loss (ml)     0.5
dtype: float64
Fann 600 rpm           106.0
Fann 300 rpm            83.0
Fann 200 rpm            73.0
Fann 100 rpm            53.0
Fann 6 rpm              26.0
Fann 3 rpm              23.0
API Fluid Loss (ml)     20.0
dtype: float64